const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
  const watchdog = setTimeout(() => { console.error('Browser verification exceeded 180 seconds'); process.exit(1); }, 180000);
  const browser = await chromium.launch({ headless: true, channel: 'msedge' });
  const out = process.argv[2];
  if (out) fs.mkdirSync(out, { recursive: true });
  const reports = [];
  try {
    for (const width of (process.env.TRADE_TEST_WIDTHS || '1440,390,360').split(',').map(Number)) {
      const page = await browser.newPage({ viewport: { width, height: 1000 } });
      page.setDefaultTimeout(15000);
      const errors = [];
      page.on('pageerror', e => errors.push(e.message));
      await page.goto('http://localhost:3000/trade');
      const map = page.locator('.trade-map');
      await page.locator('.trade-map[data-ready="true"]').waitFor({timeout:60000});
      await page.waitForTimeout(1000);
      await page.getByRole('button',{name:'국가 목록 열기',exact:true}).click();
      assert(await page.getByLabel('국가 목록',{exact:true}).isVisible());
      assert.match(await page.getByLabel('국가 목록',{exact:true}).innerText(),/말레이시아/);
      await page.getByRole('button',{name:'국가 목록 닫기',exact:true}).click();
      assert.equal(await page.getByLabel('국가 목록',{exact:true}).count(),0);
      const pixels = await page.locator('.trade-map canvas').evaluate(canvas => {
        const gl = canvas.getContext('webgl2');
        const data = new Uint8Array(gl.drawingBufferWidth * gl.drawingBufferHeight * 4);
        gl.readPixels(0,0,gl.drawingBufferWidth,gl.drawingBufferHeight,gl.RGBA,gl.UNSIGNED_BYTE,data);
        let colored=0, texture=0;
        for(let i=0;i<data.length;i+=4) {
          if(data[i+3]>50 && Math.max(data[i],data[i+1],data[i+2])-Math.min(data[i],data[i+1],data[i+2])>30) colored++;
          if(data[i+3]>50 && data[i+1]>data[i]*1.1 && data[i+1]>data[i+2]*1.05) texture++;
        }
        return {colored,texture};
      });
      assert(pixels.colored>500, 'Highlighted export countries must render');
      const lon1 = Number(await map.getAttribute('data-longitude'));
      await page.waitForTimeout(900);
      const lon2 = Number(await map.getAttribute('data-longitude'));
      assert(Math.abs(lon1-lon2)>0.05, 'Auto rotation must move globe, not just arcs');
      await page.getByRole('button',{name:'자동 회전 정지',exact:true}).click();
      const alt = Number(await map.getAttribute('data-altitude'));
      await page.getByRole('button',{name:'지도 확대',exact:true}).click();
      await page.waitForTimeout(700);
      assert(Number(await map.getAttribute('data-altitude'))<alt, 'Zoom must move camera');
      await map.scrollIntoViewIfNeeded();
      const bounds=await map.boundingBox();
      const beforeDrag=Number(await map.getAttribute('data-longitude'));
      await page.mouse.move(bounds.x+bounds.width/2,bounds.y+bounds.height/2);
      await page.mouse.down();
      await page.mouse.move(bounds.x+bounds.width/2+65,bounds.y+bounds.height/2+12,{steps:12});
      await page.mouse.up();
      await page.waitForTimeout(800);
      assert(Math.abs(Number(await map.getAttribute('data-longitude'))-beforeDrag)>1, 'Drag must rotate globe');
      await page.getByRole('button',{name:'지도 초기화',exact:true}).click();
      await page.waitForTimeout(800);
      if(out) await page.screenshot({path:out+'/globe-'+width+'.png',fullPage:true});
      assert.equal(await page.getByRole('button',{name:'수출선 숨기기',exact:true}).count(),0);
      await page.getByRole('button',{name:'밝은 지도',exact:true}).click();
      assert.equal(await page.locator('.globe-wrap').getAttribute('data-theme'),'light');
      await page.waitForTimeout(700);
      assert.equal(await map.getAttribute('data-surface'),'pale');
      const palePixels = await map.locator('canvas').evaluate(canvas => {
        const gl = canvas.getContext('webgl2'), data = new Uint8Array(gl.drawingBufferWidth * gl.drawingBufferHeight * 4);
        gl.readPixels(0,0,gl.drawingBufferWidth,gl.drawingBufferHeight,gl.RGBA,gl.UNSIGNED_BYTE,data);
        let count = 0;
        for (let i=0; i<data.length; i+=4) if(data[i+3]>240 && data[i]>145 && data[i+1]>145 && data[i+2]>145) count++;
        return count;
      });
      assert(palePixels>10000,'Light mode must change the globe surface, not just its backdrop');
      const flag = page.locator('img.map-origin-flag');
      assert.equal(await flag.getAttribute('alt'),'대한민국 국기');
      assert(await flag.evaluate(img => img.complete && img.naturalWidth>0),'Local flag asset must load');
      if(out) await page.screenshot({path:out+'/globe-light-'+width+'.png',fullPage:true});
      await page.getByRole('button',{name:'어두운 지도',exact:true}).click();
      await page.getByRole('button',{name:'평면 지도로 보기',exact:true}).click();
      const flat = page.locator('.trade-flat-map');
      await page.locator('.trade-flat-map[data-ready="true"]').waitFor();
      await page.waitForTimeout(1300);
      assert.equal(await flat.getAttribute('data-progress'),'1.000');
      assert(Number(await flat.getAttribute('data-bar-count'))>10);
      const flatPixels=await flat.locator('canvas').evaluate(canvas=>{
        const gl=canvas.getContext('webgl2');
        const data=new Uint8Array(gl.drawingBufferWidth*gl.drawingBufferHeight*4);
        gl.readPixels(0,0,gl.drawingBufferWidth,gl.drawingBufferHeight,gl.RGBA,gl.UNSIGNED_BYTE,data);
        let count=0;
        for(let i=0;i<data.length;i+=4) if(data[i+3]>50 && Math.max(data[i],data[i+1],data[i+2])-Math.min(data[i],data[i+1],data[i+2])>40) count++;
        return count;
      });
      if(out) await page.screenshot({path:out+'/flat-'+width+'.png',fullPage:true});
      assert(flatPixels>500,`Flat countries and bars must render (${width}px: ${flatPixels} colored pixels)`);
      await page.getByRole('button',{name:'어두운 지도',exact:true}).click();
      await page.waitForTimeout(1100);
      if(out) await page.screenshot({path:out+'/flat-dark-'+width+'.png',fullPage:true});
      await page.getByRole('button',{name:'밝은 지도',exact:true}).click();
      await page.getByRole('button',{name:'지도 확대',exact:true}).click();
      await page.waitForTimeout(300);
      assert(Number(await flat.getAttribute('data-zoom'))>1);
      await flat.scrollIntoViewIfNeeded();
      const flatBounds=await flat.boundingBox();
      const pan=Number(await flat.getAttribute('data-pan'));
      await page.mouse.move(flatBounds.x+flatBounds.width/2,flatBounds.y+flatBounds.height/2);
      await page.mouse.down();
      await page.mouse.move(flatBounds.x+flatBounds.width/2+50,flatBounds.y+flatBounds.height/2,{steps:10});
      await page.mouse.up();
      await page.waitForTimeout(300);
      assert(Math.abs(Number(await flat.getAttribute('data-pan'))-pan)>1,'Flat map must pan');
      await page.getByRole('button',{name:'지도 초기화',exact:true}).click();
      await page.getByRole('button',{name:'지구본으로 보기',exact:true}).click();
      await page.waitForTimeout(1000);
      assert.equal(await page.locator('.globe-wrap').getAttribute('data-view'),'globe');
      assert.match(await page.locator('.map-legend').innerText(),/제곱근 보정/);
      await page.getByLabel('수출 대상국').selectOption('BR');
      await page.waitForTimeout(1200);
      assert.match(await page.locator('.trade-kpis').innerText(),/브라질/);
      assert.equal(await page.locator('.map-country-label').innerText(),'브라질');
      assert(Number(await map.getAttribute('data-longitude'))<0,'Country selection flies to Brazil');
      await page.getByRole('button',{name:'지도 화면 확대',exact:true}).click();
      assert(await page.locator('.globe-expanded').isVisible());
      await page.waitForTimeout(1500);
      const fullscreenBox=await page.locator('.globe-expanded').boundingBox();
      assert.equal(fullscreenBox.x,0); assert.equal(fullscreenBox.y,0);
      assert.equal(Math.round(fullscreenBox.width),width);
      assert.equal(Math.round(fullscreenBox.height),1000);
      assert(await page.getByLabel('전체화면 국가 목록').isVisible());
      await page.getByRole('button',{name:'국가 목록 닫기',exact:true}).click();
      assert.equal(await page.getByLabel('전체화면 국가 목록').count(),0);
      await page.getByRole('button',{name:'국가 목록 열기',exact:true}).click();
      await page.getByLabel('전체화면 국가 목록').getByRole('button').filter({hasText:'미국'}).click();
      await page.waitForTimeout(1100);
      assert(Number(await map.getAttribute('data-longitude'))<0,'Fullscreen list flies to country');
      if(out) await page.screenshot({path:out+'/fullscreen-'+width+'.png'});
      await page.getByRole('button',{name:'지도 화면 축소',exact:true}).click();
      await page.locator('.globe-expanded').waitFor({state:'detached'});
      assert.equal(await page.locator('.globe-expanded').count(),0);
      await page.getByLabel('수출 품목').selectOption('beauty');
      await page.locator('.trade-map[data-ready="true"]').waitFor();
      assert((await page.getByLabel('수출 대상국').locator('option').count())>100);
      assert((await page.getByLabel('수출 대상국').locator('option').count())<200);
      assert.equal(await page.locator('.bar-prior').count(),0);
      await page.getByLabel('차트 지표').selectOption('usdPerKg');
      assert.match(await page.locator('.trade-weight-summary').innerText(),/달러\/kg/);
      await page.getByLabel('차트 지표').selectOption('value');
      assert((await page.locator('.trade-country-table tbody tr').count())>100);
      await page.getByLabel('대륙 필터').selectOption('Europe');
      const europeCount=await page.locator('.trade-country-table tbody tr').count();
      assert(europeCount>10 && europeCount<100);
      await page.getByLabel('국가 검색').fill('독일');
      assert.equal(await page.locator('.trade-country-table tbody tr').count(),1);
      await page.getByLabel('국가 검색').fill('');
      await page.getByLabel('대륙 필터').selectOption('all');
      await page.getByRole('button',{name:'평면 지도로 보기',exact:true}).click();
      await page.waitForTimeout(1300);
      assert(Number(await flat.getAttribute('data-bar-count'))>100,'All beauty destinations on flat map');
      await page.getByLabel('대륙 필터').selectOption('Europe');
      await page.waitForTimeout(300);
      assert(Number(await flat.getAttribute('data-bar-count'))<60,'Flat map follows region filter');
      await page.getByLabel('대륙 필터').selectOption('all');
      await page.getByRole('button',{name:'지구본으로 보기',exact:true}).click();
      await page.waitForTimeout(1000);
      if(out) await page.screenshot({path:out+'/beauty-'+width+'.png',fullPage:true});
      assert.equal(await page.locator('.trade-scope').count(),0);
      await page.getByLabel('시작월',{exact:true}).selectOption('2026-04');
      await page.getByLabel('종료월',{exact:true}).selectOption('2026-05');
      const beauty = JSON.parse(fs.readFileSync('data/trade/beauty.json','utf8'));
      const amount = beauty.monthlyTotals['2026-04'] + beauty.monthlyTotals['2026-05'];
      const { usdText } = await import('../lib/trade.ts');
      assert.match(await page.locator('.trade-kpis').innerText(),/2026.04 ~ 2026.05/);
      assert.equal(await page.locator('.trade-kpis strong').first().innerText(),usdText(amount));
      const downloadEvent = page.waitForEvent('download');
      await page.getByRole('button',{name:'CSV 다운로드',exact:true}).click();
      const download = await downloadEvent;
      let csv = '';
      for await (const chunk of await download.createReadStream()) csv += chunk;
      const csvRows = csv.trim().split('\n').slice(1);
      assert(csvRows.length>0 && csvRows.every(r => ['2026-04','2026-05'].includes(r.split(',')[1])));
      assert.equal(download.suggestedFilename(),'beauty-2026-04-2026-05.csv');
      const weights = beauty.monthlyWeightTotals['2026-04'] + beauty.monthlyWeightTotals['2026-05'];
      assert.match(await page.locator('.trade-weight-summary').innerText(),new RegExp(Math.round(amount/weights).toLocaleString('ko-KR')));
      assert.equal(await page.getByLabel('수출 대상국').inputValue(),'all');
      if(out) await page.screenshot({path:out+'/range-'+width+'.png',fullPage:true});
      await page.getByLabel('시작월',{exact:true}).selectOption('2026-07');
      assert.equal(await page.getByLabel('종료월',{exact:true}).inputValue(),'2026-07');
      await page.getByLabel('수출 품목').selectOption('transformer');
      await page.locator('.trade-map[data-ready="true"]').waitFor();
      assert.match(await page.locator('.trade-subject').innerText(),/8504230000/);
      assert((await page.locator('.trade-country-table tbody tr').count())>0);
      assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No horizontal page overflow');
      assert.deepEqual(errors,[]);
      reports.push({width,pixels,flatPixels,flatTransition:true,flatPanZoom:true,rotation:true,drag:true,zoom:true,allCountries:true,europeCount,errors});
      await page.close();
    }
    console.log(JSON.stringify(reports,null,2));
  } finally { clearTimeout(watchdog); await browser.close(); }
})().catch(e=>{console.error(e);process.exit(1)});
